waku:
  nodes:
    readinessProbe:
      presets:
        health: "include:waku.nodes.readiness-probe.health"
        metrics: "include:waku.nodes.readiness-probe.metrics"
        jswaku: "include:waku.nodes.readiness-probe.jswaku"