apiVersion: v1
kind: Service
metadata:
  name: zerotesting-publisher
  namespace: zerotesting-pwhite
spec:
  type: NodePort
  selector:
    app: zerotenkay-publisher
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8645
    nodePort: 30080