apiVersion: v1
kind: Service
metadata:
  name: zerotesting-service
  namespace: rln-test
spec:
  clusterIP: None
  selector:
    app: rln-nodes
  ports:
  - protocol: TCP
    port: 8645
    targetPort: 8645